In [ ]:
# Importing Needed packages
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from google.colab import files
from sklearn.impute import KNNImputer
from sklearn.impute import SimpleImputer
from random import *
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import fbeta_score
from sklearn.utils import shuffle
from sklearn.mixture import GaussianMixture
from imblearn.under_sampling import NearMiss
#from imblearn.over_sampling import SMOTENC
from imblearn.combine import SMOTEENN
from imblearn.under_sampling import ClusterCentroids
from imblearn.under_sampling import RandomUnderSampler 
from imblearn.under_sampling import EditedNearestNeighbours
from imblearn.under_sampling import RepeatedEditedNearestNeighbours
from imblearn.under_sampling import AllKNN
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE, ADASYN
from sklearn.svm import OneClassSVM

In [ ]:
pip install -U imbalanced-learn

Collecting imbalanced-learn
  Downloading https://files.pythonhosted.org/packages/80/98/dc784205a7e3034e84d41ac4781660c67ad6327f2f5a80c568df31673d1c/imbalanced_learn-0.8.0-py3-none-any.whl (206kB)
     |████████████████████████████████| 215kB 16.0MB/s
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (1.19.5)
Collecting scikit-learn>=0.24
  Downloading https://files.pythonhosted.org/packages/a8/eb/a48f25c967526b66d5f1fa7a984594f0bf0a5afafa94a8c4dbc317744620/scikit_learn-0.24.2-cp37-cp37m-manylinux2010_x86_64.whl (22.3MB)
     |████████████████████████████████| 22.3MB 1.6MB/s
Requirement already satisfied, skipping upgrade: scipy>=0.19.1 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (1.4.1)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (1.0.1)
Collecting threadpoolctl>=2.0.0
  Downloading https://files.pythonhosted.org/packages/f7/12/ec3f2e203afa394a149911729357aa48affc59c20e2c1c8297a60f33f133/threadpoolctl-2.1.0-py3-none-any.whl
Installing collected packages: threadpoolctl, scikit-learn, imbalanced-learn
  Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1
  Found existing installation: imbalanced-learn 0.4.3
    Uninstalling imbalanced-learn-0.4.3:
      Successfully uninstalled imbalanced-learn-0.4.3
Successfully installed imbalanced-learn-0.8.0 scikit-learn-0.24.2 threadpoolctl-2.1.0

In [ ]:
nm1 = NearMiss(version=1)
X_resampled_nm1, y_resampled = nm1.fit_resample(X, y)

In [ ]:
#colab上傳檔案
from google.colab import files
upload = files.upload()

Saving season.csv to season.csv
Saving submission.csv to submission.csv
Saving test.csv to test.csv
Saving train.csv to train.csv

In [ ]:
#
df_ori = pd.read_csv("train.csv")
df_ori.loc[df_ori["最高學歷"].isnull()].loc[df_ori["PerStatus"]==1].groupby("yyyy").size()

yyyy
2014    91
2015    73
2016    79
2017    60
dtype: int64

In [ ]:
#各feature空值
df_ori = pd.read_csv("train.csv")
df_ori.loc[df_ori.sex.notnull()].isnull().sum()

yyyy            0
PerNo           0
PerStatus       0
sex             0
工作分類            0
職等              0
廠區代碼            0
管理層級            0
工作資歷1           0
工作資歷2           0
工作資歷3           0
工作資歷4           0
工作資歷5           0
專案時數            0
專案總數            0
當前專案角色          0
特殊專案佔比          0
工作地點            0
訓練時數A           0
訓練時數B           0
訓練時數C           0
生產總額            0
榮譽數             0
是否升遷            0
升遷速度            0
近三月請假數A         0
近一年請假數A         0
近三月請假數B         0
近一年請假數B         0
出差數A            0
出差數B            0
出差集中度           0
年度績效等級A         0
年度績效等級B         0
年度績效等級C         0
年齡層級            0
婚姻狀況            0
年資層級A           0
年資層級B           0
年資層級C           0
任職前工作平均年數       0
最高學歷         5253
畢業學校類別       3768
畢業科系類別          0
眷屬量             0
通勤成本            0
歸屬部門            0
dtype: int64

In [ ]:
df = pd.read_csv("train.csv")
df.head()

   yyyy  PerNo  PerStatus  sex  工作分類  ...  畢業學校類別  畢業科系類別  眷屬量  通勤成本     歸屬部門
0  2014      1          0  1.0   1.0  ...     NaN     5.0  0.0   8.0  19138.0
1  2015      1          0  1.0   1.0  ...     NaN     5.0  2.0   8.0  19138.0
2  2016      1          0  1.0   1.0  ...     NaN     5.0  2.0   8.0  19138.0
3  2017      1          0  1.0   1.0  ...     NaN     5.0  2.0   8.0  19138.0
4  2014      3          0  0.0   1.0  ...     4.0     1.0  2.0   8.0   8181.0

[5 rows x 47 columns]

In [ ]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

DDF = imp_mean.fit_transform(df)

df.loc[:] = DDF

df

         yyyy   PerNo  PerStatus  sex  工作分類  ...  畢業學校類別  畢業科系類別  眷屬量  通勤成本     歸屬部門
0      2014.0     1.0        0.0  1.0   1.0  ...     4.0     5.0  0.0   8.0  19138.0
1      2015.0     1.0        0.0  1.0   1.0  ...     4.0     5.0  2.0   8.0  19138.0
2      2016.0     1.0        0.0  1.0   1.0  ...     4.0     5.0  2.0   8.0  19138.0
3      2017.0     1.0        0.0  1.0   1.0  ...     4.0     5.0  2.0   8.0  19138.0
4      2014.0     3.0        0.0  0.0   1.0  ...     4.0     1.0  2.0   8.0   8181.0
...       ...     ...        ...  ...   ...  ...     ...     ...  ...   ...      ...
14387  2014.0  8774.0        0.0  1.0   1.0  ...     3.0     8.0  2.0   8.0   8012.0
14388  2015.0  8774.0        0.0  1.0   1.0  ...     3.0     8.0  2.0   8.0   8012.0
14389  2016.0  8774.0        0.0  1.0   1.0  ...     3.0     8.0  2.0   8.0   8012.0
14390  2017.0  8774.0        0.0  1.0   1.0  ...     3.0     8.0  2.0   8.0   8012.0
14391  2017.0  8775.0        0.0  1.0   2.0  ...     3.0     8.0  0.0   9.0   8206.0

[14392 rows x 47 columns]

In [ ]:

df_s = pd.read_csv("submission.csv")

randBinList = lambda n: [randint(0,1) for b in range(1,n+1)]
YY = randBinList(3739)
for i,j in enumerate(YY):
  if j == 0:
    YY[i]=1



df_s.PerStatus.loc[:] = YY


df_s.to_csv('S2.csv', index=False)
files.download('S2.csv')

FileNotFoundError: ignored

In [ ]:

df_gr = df.groupby("PerNo").last()
df_gr
#取每個group
#gl = df.sort_values("yyyy").groupby("PerNo").first()
#gl

          yyyy  PerStatus  sex  工作分類   職等  ...  畢業學校類別  畢業科系類別  眷屬量  通勤成本     歸屬部門
PerNo                                      ...
1.0     2017.0        0.0  1.0   1.0  3.0  ...     4.0     5.0  2.0   8.0  19138.0
3.0     2017.0        0.0  0.0   1.0  4.0  ...     4.0     1.0  2.0   8.0   8181.0
6.0     2016.0        0.0  1.0   1.0  7.0  ...     4.0     8.0  1.0   8.0  14048.0
7.0     2017.0        0.0  0.0   1.0  4.0  ...     4.0     5.0  0.0  10.0   4045.0
10.0    2016.0        0.0  1.0   1.0  3.0  ...     4.0     8.0  0.0   8.0   8157.0
...        ...        ...  ...   ...  ...  ...     ...     ...  ...   ...      ...
8767.0  2017.0        0.0  1.0   1.0  4.0  ...     4.0     7.0  0.0   8.0  13084.0
8768.0  2015.0        0.0  1.0   1.0  3.0  ...     5.0     3.0  2.0   9.0  14053.0
8769.0  2016.0        1.0  1.0   1.0  7.0  ...     4.0     8.0  1.0   8.0   8038.0
8774.0  2017.0        0.0  1.0   1.0  7.0  ...     3.0     8.0  2.0   8.0   8012.0
8775.0  2017.0        0.0  1.0   2.0  2.0  ...     3.0     8.0  0.0   9.0   8206.0

[4600 rows x 46 columns]

In [ ]:
df.groupby("yyyy").size()

yyyy
2014.0    3499
2015.0    3581
2016.0    3638
2017.0    3674
dtype: int64

In [ ]:
df.loc[df.PerStatus==1].groupby("yyyy").size()

yyyy
2014.0    238
2015.0    183
2016.0    200
2017.0    175
dtype: int64

In [ ]:
print(((238/3499)+(183/3581)+(200/3638)+(175/3674))/4 )

0.055432436952220235

In [ ]:
int(3739*0.05543243695)
#207
ans = np.zeros(3739)
for i in range(207):
    ans[i]=1
np.random.shuffle(ans)
#ans
df_ss = pd.read_csv("submission.csv")
df_ss.PerStatus.loc[:] = ans
df_ss.to_csv('SS.csv', index=False)
files.download('SS.csv')

In [ ]:
ass = df.loc[df["最高學歷"]==2]
print(ass)
ass.loc[df["PerStatus"]==1].groupby("yyyy").size()

         yyyy   PerNo  PerStatus  sex  工作分類  ...  畢業學校類別  畢業科系類別  眷屬量  通勤成本     歸屬部門
0      2014.0     1.0        0.0  1.0   1.0  ...     4.0     5.0  0.0   8.0  19138.0
1      2015.0     1.0        0.0  1.0   1.0  ...     4.0     5.0  2.0   8.0  19138.0
2      2016.0     1.0        0.0  1.0   1.0  ...     4.0     5.0  2.0   8.0  19138.0
3      2017.0     1.0        0.0  1.0   1.0  ...     4.0     5.0  2.0   8.0  19138.0
4      2014.0     3.0        0.0  0.0   1.0  ...     4.0     1.0  2.0   8.0   8181.0
...       ...     ...        ...  ...   ...  ...     ...     ...  ...   ...      ...
14383  2017.0  8767.0        0.0  1.0   1.0  ...     4.0     7.0  0.0   8.0  13084.0
14384  2015.0  8768.0        0.0  1.0   1.0  ...     5.0     3.0  2.0   9.0  14053.0
14385  2015.0  8769.0        0.0  1.0   1.0  ...     4.0     8.0  1.0   8.0   8038.0
14386  2016.0  8769.0        1.0  1.0   1.0  ...     4.0     8.0  1.0   8.0   8038.0
14391  2017.0  8775.0        0.0  1.0   2.0  ...     3.0     8.0  0.0   9.0   8206.0

[13480 rows x 47 columns]

yyyy
2014.0    229
2015.0    179
2016.0    198
2017.0    169
dtype: int64

In [ ]:
df = pd.read_csv("train.csv")
dd_2014 = dfsea_2014.get_group(1).mean().to_frame().T
dd_2018 = dfsea_2018.get_group(1).mean().to_frame().T
dd = pd.concat([dd_2014,dd_2018])
AA = pd.merge(df, dd, on=['yyyy', 'PerNo'], how='left')
AA

NameError: ignored

In [ ]:
#年加班數
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")
df_season = pd.read_csv("season.csv")
df_season["PN"] = df_season["PerNo"]
df_season = df_season[["PN","yyyy","PerNo","加班數"]]

sea_2014 = df_season.loc[df_season["yyyy"]==2014].groupby("PN")
sea_2015 = df_season.loc[df_season["yyyy"]==2015].groupby("PN")
sea_2016 = df_season.loc[df_season["yyyy"]==2016].groupby("PN")
sea_2017 = df_season.loc[df_season["yyyy"]==2017].groupby("PN")
sea_2018 = df_season.loc[df_season["yyyy"]==2018].groupby("PN")

dfsea_2014 = pd.concat([sea_2014.mean()[["yyyy","PerNo"]],sea_2014.sum()["加班數"]],axis=1)
dfsea_2015 = pd.concat([sea_2015.mean()[["yyyy","PerNo"]],sea_2015.sum()["加班數"]],axis=1)
dfsea_2016 = pd.concat([sea_2016.mean()[["yyyy","PerNo"]],sea_2016.sum()["加班數"]],axis=1)
dfsea_2017 = pd.concat([sea_2017.mean()[["yyyy","PerNo"]],sea_2017.sum()["加班數"]],axis=1)
dfsea_2018 = pd.concat([sea_2018.mean()[["yyyy","PerNo"]],sea_2018.sum()["加班數"]],axis=1)

dfsea = pd.concat([dfsea_2014,dfsea_2015,dfsea_2016,dfsea_2017])
all_train = pd.merge(df_train, dfsea, on=['yyyy', 'PerNo'], how='left')
all_test = pd.merge(df_test, dfsea_2018 , on=['yyyy', 'PerNo'], how='left')

In [ ]:
#高斯
df_submission = pd.read_csv("submission.csv")
df_tr = all_train

df_train = df_tr.loc[df_tr.sex.notnull()]
df_test = all_test
#test填空值
df_test = df_test[["職等","專案總數","生產總額","升遷速度","近三月請假數A","出差集中度","年度績效等級A","年度績效等級B","年度績效等級C","年齡層級","年資層級A","年資層級B"]]
#df_test = df_test[['職等','專案時數','專案總數','特殊專案佔比','訓練時數C','升遷速度','近三月請假數A','近一年請假數A','近一年請假數B','出差數A','年度績效等級C','年齡層級','年資層級A','年資層級B','眷屬量']]
#df_test = df_test[['職等','專案時數','專案總數','特殊專案佔比','訓練時數C','生產總額','榮譽數','升遷速度','近三月請假數A','近一年請假數A','出差數A','出差數B','出差集中度','年度績效等級B','年齡層級','年資層級A','任職前工作平均年數','通勤成本']]
#df_test = df_test['職等','管理層級','專案時數','專案總數','特殊專案佔比','訓練時數C','生產總額','榮譽數','升遷速度','近三月請假數A','近一年請假數A','出差數A','出差數B','出差集中度','年度績效等級B','年齡層級','年資層級A','任職前工作平均年數','通勤成本',"加班數"]
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
x_predict = imp_mean.fit_transform(df_test)

#選feature(線性)
df_train_x = df_train[["職等","專案總數","生產總額","升遷速度","近三月請假數A","出差集中度","年度績效等級A","年度績效等級B","年度績效等級C","年齡層級","年資層級A","年資層級B"]]
df_train_y = df_train["PerStatus"]
x_train, x_test, y_train, y_test = train_test_split(df_train_x.values, df_train_y.values, test_size=0.3)
y_train = np.array(y_train, dtype=int)
y_test = np.array(y_test, dtype=int)

#正規
x_train = preprocessing.normalize(x_train, norm='l1')
x_test = preprocessing.normalize(x_test, norm='l1')
x_predict = preprocessing.normalize(x_predict, norm='l1')

knn = GaussianNB()
knn.fit(x_train,y_train)
y_pred_knn = knn.predict(x_test)

#accuracy_score
score_knn = accuracy_score(y_test, y_pred_knn)
print("score_GNB: ",score_knn)

#zero_f_score
zf_pre = abs(y_pred_knn-1)
zf_yt = abs(y_test-1)
zfb_score = f1_score(zf_yt, zf_pre, average='binary')
print("zero_f_score: ",zfb_score)

#f_score
f_score = f1_score(y_test, y_pred_knn, average='binary')
print("f_score: ",f_score)

#f_beta_score
fb_score = fbeta_score(y_test, y_pred_knn, average='binary', beta=1.5)
print("fbeta_score: ",fb_score)
#cross_val_score
#knn_cv = KNeighborsClassifier()
#cv_scores = cross_val_score(knn_cv, x_train, y_train, cv=10)
#print('cv_scores mean:{}' .format(np.mean(cv_scores)))

#test預測
y_pred_knn = knn.predict(x_predict)
df_submission.PerStatus[:] = y_pred_knn
df_submission.to_csv('SS.csv', index=False)
#files.download('SS.csv')
print("number of 1:",y_pred_knn.sum())

score_GNB:  0.9315642458100558
zero_f_score:  0.9643463497453311
f_score:  0.15028901734104047
fbeta_score:  0.13105854982551376
number of 1: 124

In [ ]:
sc = 0
fs = 0
fbs = 0
df_submission = pd.read_csv("submission.csv")
df_tr = all_train
df_train = df_tr.loc[df_tr.sex.notnull()]
df_test = all_test
df_test = df_test[["職等","專案總數","生產總額","升遷速度","近三月請假數A","出差集中度","年度績效等級A","年度績效等級B","年度績效等級C","年齡層級","年資層級A","年資層級B","畢業科系類別"]]
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
x_predict = imp_mean.fit_transform(df_test)
df_train_x = df_train[["職等","專案總數","生產總額","升遷速度","近三月請假數A","出差集中度","年度績效等級A","年度績效等級B","年度績效等級C","年齡層級","年資層級A","年資層級B","畢業科系類別"]]
df_train_y = df_train["PerStatus"]
for i in range(1000):

  x_train, x_test, y_train, y_test = train_test_split(df_train_x.values, df_train_y.values, test_size=0.3)
  y_train = np.array(y_train, dtype=int)
  y_test = np.array(y_test, dtype=int)
  x_train = preprocessing.normalize(x_train, norm='l1')
  x_test = preprocessing.normalize(x_test, norm='l1')
  x_predict = preprocessing.normalize(x_predict, norm='l1')
  knn = GaussianNB()
  knn.fit(x_train,y_train)
  y_pred_knn = knn.predict(x_test)
  score_knn = accuracy_score(y_test, y_pred_knn)
  f_score = f1_score(y_test, y_pred_knn, average='binary')
  fb_score = fbeta_score(y_test, y_pred_knn, average='binary', beta=1.5)
  if fb_score>fbs and fb_score>f_score:
    yp = knn.predict(x_predict)
    sc = score_knn
    fs = f_score
    fbs = fb_score

print("score_knn:",sc)
print("f_score:",fs)
print("fbeta_score:",fbs)
df_submission.PerStatus[:] = yp
df_submission.to_csv('SS.csv', index=False)
print(yp.sum())

score_knn: 0.9145716945996276
f_score: 0.1070559610705596
fbeta_score: 0.10735735735735735
199

In [ ]:
files.download('SS.csv')

In [ ]:
#PCA
pca = PCA(.95)
pca.fit(x_train)
x_train = pca.transform(x_train)
x_test = pca.transform(x_test)
x_predict = pca.transform(x_predict)

print(pca.explained_variance_ratio_)

print(pca.explained_variance_)

[1.]
[31395441.97988834]

In [ ]:
#樣本平衡(直接刪) 高斯
df_submission = pd.read_csv("submission.csv")
df_tr = all_train
DDD = df_tr.loc[df_tr["PerStatus"]==0]
##
#DDD_4 = shuffle(DDD.loc[DDD.yyyy==2014])
#DDD_5 = shuffle(DDD.loc[DDD.yyyy==2015])
#DDD_6 = shuffle(DDD.loc[DDD.yyyy==2016])
#DDD_7 = shuffle(DDD.loc[DDD.yyyy==2017])
##
DDD = shuffle(DDD)

DDD = DDD[0:5000]
DDD = pd.concat([DDD,df_tr.loc[df_tr["PerStatus"]==1]])
DDD = shuffle(DDD)
#print(DDD)
df_tr = DDD
df_train = df_tr.loc[df_tr.sex.notnull()]
df_test = all_test
#test填空值
df_test = df_test[["職等","專案總數","生產總額","升遷速度","近三月請假數A","出差集中度","年度績效等級A","年度績效等級B","年度績效等級C","年齡層級","年資層級A","年資層級B","畢業科系類別"]]
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
x_predict = imp_mean.fit_transform(df_test)
#選feature(線性)
df_train_x = df_train[["職等","專案總數","生產總額","升遷速度","近三月請假數A","出差集中度","年度績效等級A","年度績效等級B","年度績效等級C","年齡層級","年資層級A","年資層級B","畢業科系類別"]]
df_train_y = df_train["PerStatus"]
#split
x_train, x_test, y_train, y_test = train_test_split(df_train_x.values, df_train_y.values, test_size=0.2)
print("yt",y_test.sum())
print("xt",y_train.sum())
y_train = np.array(y_train, dtype=int)
y_test = np.array(y_test, dtype=int)

#正規
x_train = preprocessing.normalize(x_train, norm='l1')
x_test = preprocessing.normalize(x_test, norm='l1')
x_predict = preprocessing.normalize(x_predict, norm='l1')

#KNeighborsClassifier
knn = GaussianNB()
knn.fit(x_train,y_train)
y_pred_knn = knn.predict(x_test)

#accuracy_score
score_knn = accuracy_score(y_test, y_pred_knn)
print("score_knn: ",score_knn)

#zero_f_score
zf_pre = abs(y_pred_knn-1)
zf_yt = abs(y_test-1)
zfb_score = f1_score(zf_yt, zf_pre, average='binary')
print("zero_f_score: ",zfb_score)

#f_score
f_score = f1_score(y_test, y_pred_knn, average='binary')
print("f_score: ",f_score)
#f_beta_score
fb_score = fbeta_score(y_test, y_pred_knn, average='binary', beta=1.5)
print("fbeta_score: ",fb_score)
#cross_val_score
#knn_cv = KNeighborsClassifier()
#cv_scores = cross_val_score(knn_cv, x_train, y_train, cv=10)
#print('cv_scores mean:{}' .format(np.mean(cv_scores)))

#test預測
y_pred_knn = knn.predict(x_predict)
df_submission.PerStatus.loc[:] = y_pred_knn
df_submission.to_csv('S2.csv', index=False)
#files.download('S2.csv')
print(y_pred_knn.sum())
print("number of 1:",y_pred_knn.sum())

yt 179
xt 614
score_knn:  0.7998266897746967
zero_f_score:  0.8846729905142287
f_score:  0.24262295081967214
fbeta_score:  0.22742316784869981
401
number of 1: 401

In [ ]:
sc = 0
zfs = 0
fs = 0
fbs = 0

for i in range(1000):
  df_submission = pd.read_csv("submission.csv")
  df_tr = all_train
  DDD = df_tr.loc[df_tr["PerStatus"]==0]
  DDD = shuffle(DDD)
  DDD = DDD[0:]
  DDD = pd.concat([DDD,df_tr.loc[df_tr["PerStatus"]==1]])
  DDD = shuffle(DDD)
  df_tr = DDD
  df_train = df_tr.loc[df_tr.sex.notnull()]
  df_test = all_test
  df_test = df_test[["職等","專案總數","生產總額","升遷速度","近三月請假數A","出差集中度","年度績效等級A","年度績效等級B","年度績效等級C","年齡層級","年資層級A","年資層級B"]]
  imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
  x_predict = imp_mean.fit_transform(df_test)
  df_train_x = df_train[["職等","專案總數","生產總額","升遷速度","近三月請假數A","出差集中度","年度績效等級A","年度績效等級B","年度績效等級C","年齡層級","年資層級A","年資層級B"]]
  df_train_y = df_train["PerStatus"]
  x_train, x_test, y_train, y_test = train_test_split(df_train_x.values, df_train_y.values, test_size=0.2)
  y_train = np.array(y_train, dtype=int)
  y_test = np.array(y_test, dtype=int)
  x_train = preprocessing.normalize(x_train, norm='l1')
  x_test = preprocessing.normalize(x_test, norm='l1')
  x_predict = preprocessing.normalize(x_predict, norm='l1')
  knn = GaussianNB()
  knn.fit(x_train,y_train)

  y_pred_knn = knn.predict(x_test)
  score_knn = accuracy_score(y_test, y_pred_knn)
  #zero_f_score
  zf_pre = abs(y_pred_knn-1)
  zf_yt = abs(y_test-1)
  zfb_score = f1_score(zf_yt, zf_pre, average='binary')
  

  f_score = f1_score(y_test, y_pred_knn, average='binary')
  fb_score = fbeta_score(y_test, y_pred_knn, average='binary', beta=1.5)
#  if 1:
  if fb_score>fbs and fb_score>f_score:
    deleted_data = DDD
    yp = knn.predict(x_predict)
    sc = score_knn
    zfs = zfb_score
    fs = f_score
    fbs = fb_score

print("score_knn:",sc)
print("zero_f_score: ",zfs)
print("f_score:",fs)
print("fbeta_score:",fbs)
df_submission.PerStatus[:] = yp
df_submission.to_csv('S2.csv', index=False)
print(yp.sum())

score_knn: 0
zero_f_score:  0
f_score: 0
fbeta_score: 0
297

In [ ]:
ans = 0.1413043
#ans = (1+2.25)*TP/(2.25*TP+3739)
#ans*(2.25*TP+3739) = (1+2.25)*TP
TP = ans*3739/(3.25-ans*2.25)
print(TP)
ANS = 0.2037953
N =348
hits = ans*(2.25+N)/3.25 
hits_rate = hits/180
print(hits)
print(hits_rate)

180.1927034828257
15.228255715384616
0.08460142064102565

In [ ]:
deleted_data.loc[deleted_data.PerStatus==0].groupby("yyyy").size()

yyyy
2014    1317
2015    1361
2016    1384
2017    1438
dtype: int64

In [ ]:
all_train.groupby("歸屬部門").size()

歸屬部門
2029.0      57
2058.0     330
2098.0      44
2101.0     142
2128.0      44
          ...
20130.0    204
20134.0     49
20184.0     61
20192.0     50
20208.0    332
Length: 122, dtype: int64

In [ ]:
files.download('S2.csv')

In [ ]:
#blway = NearMiss(version=2,ratio=0.15925)
blway = NearMiss(version=2,sampling_strategy = 0.1595)
#blway = ClusterCentroids(random_state=42,ratio=0.15925)
#blway = SMOTEENN(random_state=0)
#樣本平衡(imblearn) 高斯
df_submission = pd.read_csv("submission.csv")
df_tr = all_train

df_train = df_tr.loc[df_tr.sex.notnull()]
df_test = all_test


#test填空值
df_test = df_test[['職等','專案時數','專案總數','特殊專案佔比','訓練時數C','升遷速度','近三月請假數A','近一年請假數A','近一年請假數B','出差數A','年度績效等級C','年齡層級','年資層級A','年資層級B','眷屬量']]
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
x_predict = imp_mean.fit_transform(df_test)
#選feature(線性)
df_train_xx = df_train[['職等','專案時數','專案總數','特殊專案佔比','訓練時數C','升遷速度','近三月請假數A','近一年請假數A','近一年請假數B','出差數A','年度績效等級C','年齡層級','年資層級A','年資層級B','眷屬量']]
df_train_yy = df_train["PerStatus"]


#正規
df_train_xx = preprocessing.normalize(df_train_xx, norm='l1')
x_predict = preprocessing.normalize(x_predict, norm='l1')

#下採樣
df_train_x, df_train_y = blway.fit_resample(df_train_xx, df_train_yy)

#split_to_validation
x_train, x_test, y_train, y_test = train_test_split(df_train_x, df_train_y, test_size=0.2)
print("yt",y_test.sum())
print("xt",y_train.sum())
y_train = np.array(y_train, dtype=int)
y_test = np.array(y_test, dtype=int)


#KNeighborsClassifier
knn = GaussianNB()
knn.fit(x_train,y_train)
y_pred_knn = knn.predict(x_test)

#accuracy_score
score_knn = accuracy_score(y_test, y_pred_knn)
print("score_knn: ",score_knn)

#f_score
f_score = f1_score(y_test, y_pred_knn, average='binary')
print("f_score: ",f_score)
#f_beta_score
fb_score = fbeta_score(y_test, y_pred_knn, average='binary', beta=1.5)
print("fbeta_score: ",fb_score)
#cross_val_score
#knn_cv = KNeighborsClassifier()
#cv_scores = cross_val_score(knn_cv, x_train, y_train, cv=10)
#print('cv_scores mean:{}' .format(np.mean(cv_scores)))

#test預測
y_pred_knn = knn.predict(x_predict)
df_submission.PerStatus.loc[:] = y_pred_knn
df_submission.to_csv('S3.csv', index=False)
print(y_pred_knn.sum())

#files.download('S3.csv')
print(x_train.shape)

yt 150
xt 643
score_knn:  0.8889852558542931
f_score:  0.6464088397790055
fbeta_score:  0.6919927206551411
1635
(4611, 15)

In [ ]:
#原樣本先分驗證集出來 再拿同樣的原樣本下採樣
#blway = NearMiss(version=2,ratio=0.15925)
#blway = RandomUnderSampler(sampling_strategy = 0.1)
#blway = NearMiss(version=2,sampling_strategy = 0.13)
#blway = ClusterCentroids(random_state=42,sampling_strategy = 0.23)
#blway = EditedNearestNeighbours(kind_sel="all")


#樣本平衡(imblearn) 高斯
df_submission = pd.read_csv("submission.csv")
df_tr = all_train


DDD = df_tr.loc[df_tr["PerStatus"]==0]
DDD = shuffle(DDD)
DDD = DDD[:]
DDD = pd.concat([DDD,df_tr.loc[df_tr["PerStatus"]==1]])
DDD = shuffle(DDD)
df_tr = DDD



df_train = df_tr.loc[df_tr.sex.notnull()]
df_test = all_test

#test填空值
df_test = df_test[['職等','專案時數','專案總數','特殊專案佔比','訓練時數C','升遷速度','近三月請假數A','近一年請假數A','近一年請假數B','出差數A','年度績效等級C','年齡層級','年資層級A','年資層級B','眷屬量']]
imp_mean = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
x_predict = imp_mean.fit_transform(df_test)
#選feature(線性)
df_train_xx = df_train[['職等','專案時數','專案總數','特殊專案佔比','訓練時數C','升遷速度','近三月請假數A','近一年請假數A','近一年請假數B','出差數A','年度績效等級C','年齡層級','年資層級A','年資層級B','眷屬量']]
df_train_yy = df_train["PerStatus"]



#split_to_validation
no_x, x_test, no_y, y_test = train_test_split(df_train_xx, df_train_yy, test_size=0.3)
#print("yt",y_test.sum())
#print("xt",y_train.sum())

#正規
df_train_xx = preprocessing.normalize(df_train_xx, norm='l1')
x_test = preprocessing.normalize(x_test, norm='l1')
x_predict = preprocessing.normalize(x_predict, norm='l1')

#下採樣
df_train_yy = np.asanyarray(df_train_yy)
#x_train, y_train = blway.fit_resample(df_train_xx, df_train_yy)


#上採樣
#x_train, y_train = SMOTE(sampling_strategy=0.2).fit_resample(df_train_xx, df_train_yy)
#x_train, y_train = RandomOverSampler(sampling_strategy=0.3).fit_resample(df_train_xx, df_train_yy)
x_train, y_train = df_train_xx, df_train_yy

y_train = np.array(y_train, dtype=int)
y_test = np.array(y_test, dtype=int)
#KNeighborsClassifier
knn = GaussianNB()
knn.fit(x_train,y_train)
y_pred_knn = knn.predict(x_test)

#accuracy_score
score_knn = accuracy_score(y_test, y_pred_knn)
print("score_knn: ",score_knn)

#f_score
f_score = f1_score(y_test, y_pred_knn, average='binary')
print("f_score: ",f_score)
#f_beta_score
fb_score = fbeta_score(y_test, y_pred_knn, average='binary', beta=1.5)
print("fbeta_score: ",fb_score)
#cross_val_score
#knn_cv = KNeighborsClassifier()
#cv_scores = cross_val_score(knn_cv, x_train, y_train, cv=10)
#print('cv_scores mean:{}' .format(np.mean(cv_scores)))

#test預測
y_pred_knn = knn.predict(x_predict)
df_submission.PerStatus.loc[:] = y_pred_knn
df_submission.to_csv('S4.csv', index=False)
#files.download('S3.csv')
print(x_train.shape)
print(y_pred_knn.sum())

score_knn:  0.9054934823091247
f_score:  0.20703125
fbeta_score:  0.2114794352363413
(14319, 15)
225

In [ ]:
files.download('S4.csv')

In [ ]:
#df_train_x

array([[0.13461538, 0.44230769, 0.01923077, ..., 0.01923077, 0.01923077,
        0.        ],
       [0.13207547, 0.45283019, 0.01886792, ..., 0.01886792, 0.01886792,
        0.        ],
       [0.12962963, 0.44444444, 0.01851852, ..., 0.01851852, 0.01851852,
        0.        ],
       ...,
       [0.04918033, 0.37704918, 0.03278689, ..., 0.04918033, 0.04918033,
        0.03278689],
       [0.06349206, 0.36507937, 0.01587302, ..., 0.03174603, 0.03174603,
        0.03174603],
       [0.11666667, 0.38333333, 0.03333333, ..., 0.01666667, 0.01666667,
        0.01666667]])

In [ ]:
files.download('S3.csv')

In [ ]:
Q = DDD.groupby("yyyy").size()
Q = np.asarray(Q)
type(Q)
print(238/(Q[0]))
print(183/(Q[1]))
print(200/(Q[2]))
print(175/(Q[3]))

0.8095238095238095
0.8133333333333334
0.7782101167315175
0.7954545454545454

In [ ]:

gra_0 = DDD.loc[DDD.PerStatus==0].PerNo
gra_1 = DDD.loc[DDD.PerStatus==1].PerNo

gr_0 = np.asarray(gra_0)
gr_1 = np.asarray(gra_1)
gdi_1 = dict.fromkeys(gr_1,)

for i in gr_0:
   if gdi_1.__contains__(i):
     print(i)  
#print(gr_0)
#print(gr_1)

1122
6915
5968
7642
1770
3491
1021
1643
1692
512
7198
6924
5953
3907
4253
4590
2577
1474

In [ ]:
#把離職員工的0去掉
ps_1 = all_train.loc[all_train["PerStatus"]==1]
ps_0 = all_train.loc[all_train["PerStatus"]==0]
index = np.asarray(ps_1.PerNo)
for i in index:
  ps_0.loc[ps_0.PerNo!=i]
ps_0

       yyyy  PerNo  PerStatus  sex  工作分類  ...  畢業科系類別  眷屬量  通勤成本     歸屬部門  加班數
0      2014      1          0  1.0   1.0  ...     5.0  0.0   8.0  19138.0    3
1      2015      1          0  1.0   1.0  ...     5.0  2.0   8.0  19138.0    1
2      2016      1          0  1.0   1.0  ...     5.0  2.0   8.0  19138.0    2
3      2017      1          0  1.0   1.0  ...     5.0  2.0   8.0  19138.0    1
4      2014      3          0  0.0   1.0  ...     1.0  2.0   8.0   8181.0    0
...     ...    ...        ...  ...   ...  ...     ...  ...   ...      ...  ...
14387  2014   8774          0  1.0   1.0  ...     8.0  2.0   8.0   8012.0    0
14388  2015   8774          0  1.0   1.0  ...     8.0  2.0   8.0   8012.0    0
14389  2016   8774          0  1.0   1.0  ...     8.0  2.0   8.0   8012.0    0
14390  2017   8774          0  1.0   1.0  ...     8.0  2.0   8.0   8012.0    4
14391  2017   8775          0  1.0   2.0  ...     8.0  0.0   9.0   8206.0    2

[13596 rows x 48 columns]

<bound method DataFrame.lookup of        yyyy  PerNo  PerStatus  sex  工作分類  ...  畢業科系類別  眷屬量  通勤成本     歸屬部門  加班數
0      2014      1          0  1.0   1.0  ...     5.0  0.0   8.0  19138.0    3
1      2015      1          0  1.0   1.0  ...     5.0  2.0   8.0  19138.0    1
2      2016      1          0  1.0   1.0  ...     5.0  2.0   8.0  19138.0    2
3      2017      1          0  1.0   1.0  ...     5.0  2.0   8.0  19138.0    1
4      2014      3          0  0.0   1.0  ...     1.0  2.0   8.0   8181.0    0
...     ...    ...        ...  ...   ...  ...     ...  ...   ...      ...  ...
14387  2014   8774          0  1.0   1.0  ...     8.0  2.0   8.0   8012.0    0
14388  2015   8774          0  1.0   1.0  ...     8.0  2.0   8.0   8012.0    0
14389  2016   8774          0  1.0   1.0  ...     8.0  2.0   8.0   8012.0    0
14390  2017   8774          0  1.0   1.0  ...     8.0  2.0   8.0   8012.0    4
14391  2017   8775          0  1.0   2.0  ...     8.0  0.0   9.0   8206.0    2

[14392 rows x 48 columns]>

In [ ]:
df_t = all_train.loc[all_train.sex.notnull()]
for i in ['yyyy','PerNo','PerStatus','sex','工作分類','職等','廠區代碼','管理層級','工作資歷1','工作資歷2','工作資歷3','工作資歷4','工作資歷5','專案時數','專案總數','當前專案角色','特殊專案佔比','工作地點','訓練時數A','訓練時數B','訓練時數C','生產總額','榮譽數','是否升遷','升遷速度','近三月請假數A','近一年請假數A','近三月請假數B','近一年請假數B','出差數A','出差數B','出差集中度','年度績效等級A','年度績效等級B','年度績效等級C','年齡層級','婚姻狀況','年資層級A','年資層級B','年資層級C','任職前工作平均年數','最高學歷','畢業學校類別','畢業科系類別','眷屬量','通勤成本','歸屬部門',"加班數"]:
  fea = i
  on = df_t[[fea]].loc[df_t["PerStatus"]==1]
  on = preprocessing.normalize(np.asanyarray(on), norm='l1')
  ze = df_t[[fea]].loc[df_t["PerStatus"]==0]
  ze = preprocessing.normalize(np.asanyarray(ze), norm='l1')
  good_f = on.mean()-ze.mean()
  print(good_f)

1.0

ValueError: ignored

In [ ]:
all_train.isnull().sum()

yyyy            0
PerNo           0
PerStatus       0
sex            24
工作分類           24
職等             24
廠區代碼           24
管理層級           24
工作資歷1          24
工作資歷2          24
工作資歷3          24
工作資歷4          24
工作資歷5          24
專案時數           24
專案總數           24
當前專案角色         24
特殊專案佔比         24
工作地點           24
訓練時數A          24
訓練時數B          24
訓練時數C          24
生產總額           24
榮譽數            24
是否升遷           24
升遷速度           24
近三月請假數A        24
近一年請假數A        24
近三月請假數B        24
近一年請假數B        24
出差數A           24
出差數B           24
出差集中度          24
年度績效等級A        24
年度績效等級B        24
年度績效等級C        24
年齡層級           24
婚姻狀況           24
年資層級A          24
年資層級B          24
年資層級C          24
任職前工作平均年數      24
最高學歷         2152
畢業學校類別       1535
畢業科系類別         24
眷屬量            24
通勤成本           24
歸屬部門           24
加班數             0
dtype: int64

In [ ]:
df_tr[['yyyy']].loc[df_tr["PerStatus"]==1]

       yyyy
3536   2016
6152   2016
6166   2014
647    2016
12302  2014
...     ...
10786  2015
822    2016
11177  2014
2498   2014
14386  2016

[796 rows x 1 columns]

In [ ]:
print(df_tr[["工作資歷1"]].sum())
print(df_tr[["工作資歷2"]].sum())
print(df_tr[["工作資歷3"]].sum())
print(df_tr[["工作資歷4"]].sum())
print(df_tr[["工作資歷5"]].sum())
print((df_tr[["婚姻狀況"]]-1).sum())
print((df_tr[["工作分類"]]-1).sum())
print(df_tr[["sex"]].sum())
print(df_tr[["是否升遷"]].sum())


print(df_tr[["工作資歷1"]].loc[df_tr["PerStatus"]==1].mean()-df_tr[["工作資歷1"]].loc[df_tr["PerStatus"]==0].mean())
print(df_tr[["工作資歷2"]].loc[df_tr["PerStatus"]==1].mean()-df_tr[["工作資歷2"]].loc[df_tr["PerStatus"]==0].mean())
print(df_tr[["工作資歷3"]].loc[df_tr["PerStatus"]==1].mean()-df_tr[["工作資歷3"]].loc[df_tr["PerStatus"]==0].mean())
print(df_tr[["工作資歷4"]].loc[df_tr["PerStatus"]==1].mean()-df_tr[["工作資歷4"]].loc[df_tr["PerStatus"]==0].mean())
print(df_tr[["工作資歷5"]].loc[df_tr["PerStatus"]==1].mean()-df_tr[["工作資歷5"]].loc[df_tr["PerStatus"]==0].mean())

print(df_tr[["婚姻狀況"]].loc[df_tr["PerStatus"]==1].mean()-df_tr[["婚姻狀況"]].loc[df_tr["PerStatus"]==0].mean())
print(df_tr[["sex"]].loc[df_tr["PerStatus"]==1].mean()-df_tr[["sex"]].loc[df_tr["PerStatus"]==0].mean())
print(df_tr[["工作分類"]].loc[df_tr["PerStatus"]==1].mean()-df_tr[["工作分類"]].loc[df_tr["PerStatus"]==0].mean())
print(df_tr[["是否升遷"]].loc[df_tr["PerStatus"]==1].mean()-df_tr[["是否升遷"]].loc[df_tr["PerStatus"]==0].mean())

工作資歷1    417.0
dtype: float64
工作資歷2    741.0
dtype: float64
工作資歷3    867.0
dtype: float64
工作資歷4    805.0
dtype: float64
工作資歷5    3276.0
dtype: float64
婚姻狀況    3693.0
dtype: float64
工作分類    1566.0
dtype: float64
sex    10042.0
dtype: float64
是否升遷    1012.0
dtype: float64
工作資歷1    0.022569
dtype: float64
工作資歷2    0.00529
dtype: float64
工作資歷3   -0.012035
dtype: float64
工作資歷4   -0.018131
dtype: float64
工作資歷5    0.130255
dtype: float64
婚姻狀況    0.139475
dtype: float64
sex    0.110621
dtype: float64
工作分類   -0.063713
dtype: float64
是否升遷    0.001274
dtype: float64

In [ ]:
fin = all_train[['yyyy','PerNo','PerStatus','sex','工作分類','職等','廠區代碼','管理層級','工作資歷1','工作資歷2','工作資歷3','工作資歷4','工作資歷5','專案時數','專案總數','當前專案角色','特殊專案佔比','工作地點','訓練時數A','訓練時數B','訓練時數C','生產總額','榮譽數','是否升遷','升遷速度','近三月請假數A','近一年請假數A','近三月請假數B','近一年請假數B','出差數A','出差數B','出差集中度','年度績效等級A','年度績效等級B','年度績效等級C','年齡層級','婚姻狀況','年資層級A','年資層級B','年資層級C','任職前工作平均年數','最高學歷','畢業學校類別','畢業科系類別','眷屬量','通勤成本','歸屬部門']]
fin.loc[fin["PerStatus"]==0].describe()

               yyyy         PerNo  ...          通勤成本          歸屬部門
count  13596.000000  13596.000000  ...  13526.000000  13526.000000
mean    2015.527729   4415.629229  ...      8.331658  12927.982182
std        1.115228   2529.704553  ...      1.238453   5617.279862
min     2014.000000      1.000000  ...      4.000000   2029.000000
25%     2015.000000   2245.000000  ...      8.000000   8145.000000
50%     2016.000000   4396.500000  ...      8.000000  14040.000000
75%     2017.000000   6613.250000  ...      8.000000  18111.000000
max     2017.000000   8775.000000  ...     16.000000  20208.000000

[8 rows x 47 columns]

In [ ]:
fin = all_train[['yyyy','PerNo','PerStatus','sex','工作分類','職等','廠區代碼','管理層級','工作資歷1','工作資歷2','工作資歷3','工作資歷4','工作資歷5','專案時數','專案總數','當前專案角色','特殊專案佔比','工作地點','訓練時數A','訓練時數B','訓練時數C','生產總額','榮譽數','是否升遷','升遷速度','近三月請假數A','近一年請假數A','近三月請假數B','近一年請假數B','出差數A','出差數B','出差集中度','年度績效等級A','年度績效等級B','年度績效等級C','年齡層級','婚姻狀況','年資層級A','年資層級B','年資層級C','任職前工作平均年數','最高學歷','畢業學校類別','畢業科系類別','眷屬量','通勤成本','歸屬部門']]
fin.loc[fin["PerStatus"]==1].describe()

              yyyy        PerNo  ...        通勤成本          歸屬部門
count   796.000000   796.000000  ...  793.000000    793.000000
mean   2015.391960  4327.510050  ...    8.358134  13011.802018
std       1.130319  2535.952424  ...    1.390030   5768.876692
min    2014.000000    11.000000  ...    4.000000   2029.000000
25%    2014.000000  2123.000000  ...    8.000000   8145.000000
50%    2015.000000  4226.000000  ...    8.000000  14040.000000
75%    2016.000000  6615.250000  ...    8.000000  19043.000000
max    2017.000000  8769.000000  ...   16.000000  20208.000000

[8 rows x 47 columns]